use_frameworks!

target 'HACMonitor_Example' do
  pod 'HACMonitor', :path => '../'

  target 'HACMonitor_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
